pacman::p_load("tidyverse","haven","labelled","here")

rp19_log=read_delim(url("https://www.isee.nc/component/phocadownload/category/193-recensement?download=2134:donnees-detaillees-rp19-open-data-logements"), 
                    delim = ";", escape_double = FALSE, trim_ws = TRUE)



# BAIL= "Type de bailleur",
#variable BAIL absente du jeu de donnees
#BAIL= c("Le logement appartient à un organisme social" = 1 ,"Le logement n’appartient pas à un organisme social"= 2 ,"Non renseigné"        = 9,



rp19_log=rp19_log %>%
  set_variable_labels(AACA = "Année d’achèvement de construction" ,
                      AACH = "Période d’achèvement de construction",
                      AEMM = "Année d’emménagement du ménage dans le logement",
                      AGERM = "Age révolu de la personne de référence du ménage",
                      ANNINSM = "Année d’installation de la personne de référence" ,
                      ASCEN = "Présence d’ascenseur" ,
                      BATI = "Aspect du bâti",
                      BAIN = "Baignoire ou douche",
                      BATO = "Nombre de bateaux",
                      CATL = "Catégorie de logement",
                      CHOM = "Nombre de chômeurs",
                      CHOS = "Equipement du logement en chauffe-eau solaire" ,
                      CLIM = "Equipement du logement en climatisation" ,
                      CS8M = "Catégorie socioprofessionnelle de la personne de référence" ,
                      CUIS = "Cuisine avec évier" ,
                      DEROU = "Deux-roues",
                      DIPLM = "Diplôme de la personne de référence" ,
                      EAU =  "Eau courante",
                      EGOUL = "Evacuation des eaux usées",
                      ELEC = "Raccordement au réseau électrique",
                      GADM = "Groupe d’âge décennal de la personne de référence" ,
                      GAQM = "Groupe d’âge quinquennal de la personne de référence" ,
                      GARL = "Emplacement réservé de stationnement" ,
                      GELG = "Equipement du logement en groupe électrogène" ,
                      GENREM = "Genre de la personne de référence" ,
                      IDLOG= "Numéro anonymisé du logement",
                      ILNM = "Indicateur du lieu de naissance de la personne de référence" ,
                      INPAM= "Nombre d’actifs",
                      INTER= "Accès internet",
                      MAL  = "Machine à laver",
                      NATM = "Nationalité de la personne de référence",
                      NBI  = "Nombre de personnes" ,
                      NBPI = "Nombre de pièces" ,
                      PEUPL = "Indicateur de peuplement" ,
                      PIEPERS = "Nombre de pièces par personne" ,
                      PROV = "Province",
                      PSOL = "Equipement du logement en panneaux solaires",
                      REFRI = "Réfrigérateur" ,
                      STOC= "Statut d’occupation du logement" ,
                      SURF = "Surface du logement" ,
                      TACTM = "Type d’activité de la personne de référence" ,
                      TFIXE = "Téléphone fixe",
                      TYPC14 = "Type de construction selon les modalités du RP 2014",
                      TYPEAU = "Type de point d’eau courante" ,
                      TYPMENR = "Type de ménage regroupé",
                      VOIT = "Nombre de voiture" ,
                      WC = "Equipement du logement en WC à l’intérieur")%>%
  set_value_labels(AACH=c("Avant 1997"= 1 ,"De 1997 à 2004"= 2,  "De 2005 à 2009"= 3 ,"De 2010 à 2014"= 4, "2015 ou après"= 5 , "Non renseigné"= 9  ),
                   ASCEN = c("Le logement est desservi par un ascenseur" =1,  "Le logement n’est pas desservi par un ascenseur" =2,  "Non renseigné"       =9), 
                   BAIN = c( "Le logement est équipé d’une baignoire ou d’une douche"=  1 , "Le logement n’est pas équipé d’une baignoire ou d’une douche"=   2 ,"Non renseigné"= 9), 
                   BATI = c("Case mélanésienne"= 1,"Habitation en tôles"=2,"Maison en bois, clin, chaux"=3,"Maison ou immeuble en dur"=4),
                   CATL = c("Résidence principale" = 1 ,"Logement occasionnel" = 2 , "Résidence secondaire" = 3 , "Logement vacant" =4), 
                   CHOS = c( "Le logement est équipé d’un chauffe-eau solaire" =1 ,"Le logement n’est pas équipé d’un chauffe-eau solaire"= 2 , "Non renseigné" = 9 ),
                   CLIM = c("Le logement est équipé en climatisation" = 1 ,"Le logement n’est pas équipé en climatisation" = 2 , "Non renseigné" =    9  ),
                   CS8M    =c("Agriculteurs exploitants" = 1 ,
                             "Artisans, commerçants et chefs d'entreprise" = 2 ,
                             "Cadres et professions intellectuelles supérieures" = 3 ,
                             "Professions Intermédiaires" = 4, 
                             "Employés" = 5, 
                             "Ouvriers"= 6 ,
                             "Retraités"=7,
                             "Autres personnes sans activité professionnelle"=8),
                   CUIS = c("Le logement dispose d’une cuisine avec évier" =   1 ,"Le logement ne dispose pas d’une cuisine avec évier" =   2 , "Non renseigné" =   9)  ,               
                   DIPLM=c("Pas de scolarisation"  = "01" ,
                           "Aucun diplôme mais scolarisation jusqu’en primaire"  = "02" ,
                           "Aucun diplôme mais scolarisation jusqu’au collège"  = "03" ,
                           "Aucun diplôme mais scolarisation au-delà du collège"  = "04" ,
                           "CEP"  = "11" ,
                           "BEPC, brevet élémentaire, brevet des collèges, DNB"  = "12" ,
                           "CAP, BEP ou diplôme de niveau équivalent"  = "13" ,
                           "Bac général ou technologique, brevet supérieur, capacité en droit, DAEU, ESEU"  = "14" ,
                           "Bac professionnel, brevet professionnel de technicien ou d’enseignement, diplôme équivalent"  = "15", 
                           "BTS, DUT, Deug, Deust, diplôme de santé ou du social niveau bac + 2, diplôme équivalent"  = "16" ,
                           "Licence, Licence pro, maîtrise, diplôme équivalent de niveau bac + 3 ou bac + 4 " = "17", 
                           "Master, DEA, diplôme grande école niveau bac + 5, doctorat de santé"= "18", 
                           "Doctorat de recherche (hors santé)" = "19"),
                   EAU = c("Le logement dispose d’un point d'eau courante" =   1 ,"Le logement ne dispose pas d’un point d'eau courante" =   2 , "Non renseigné" =   9)  ,               
                   EGOUL = c("Par raccordement au réseau d’égouts" =1 ,"Par raccordement à une fosse septique ou à une station individuelle"=2 , "A même le sol ou puisard" =3 , "Non renseigné"  =         9),
                   ELEC = c("Le logement dispose d’un raccordement au réseau électrique" =   1 ,"Le logement ne dispose pas d’un raccordement au réseau électrique" =   2 , "Non renseigné" =   9)  ,               
                   
                    GADM=c("0 à 9 ans"  = 0 ,
                         "10 à 19 ans"  = 1 ,
                         "20 à 29 ans"  = 2 ,
                         "30 à 39 ans"  = 3 ,
                         "40 à 49 ans"  = 4 ,
                         "50 à 59 ans"  = 5 ,
                         "60 à 69 ans"  = 6 ,
                         "70 à 79 ans"  = 7, 
                         "80 à 89 ans"  = 8 ,
                         "90 ans ou " = 9),
                   GAQM = c("0 à 4 ans"  = 0 ,
                           "5 à 9 ans"  = 1 ,
                           "10 à 14 ans"  = 2 ,
                           "15 à 19 ans"  = 3 ,
                           "20 à 24 ans"  = 4 ,
                           "25 à 29 ans"  = 5 ,
                           "30 à 34 ans"  = 6 ,
                           "35 à 39 ans"  = 7 ,
                           "40 à 44 ans"  = 8 ,
                           "45 à 49 ans"  = 9 ,
                           "50 à 54 ans"  = 10, 
                           "55 à 59 ans"  = 11, 
                           "60 à 64 ans"  = 12, 
                           "65 à 69 ans"  = 13, 
                           "70 à 74 ans"  = 14, 
                           "75 à 79 ans"  = 15, 
                           "80 à 84 ans"  = 16, 
                           "85 à 89 ans"  = 17, 
                           "90 à 94 ans"  = 18, 
                           "95 ans ou +" = 19),
                   GARL = c("Le ménage dispose d’un emplacement réservé à son usage personnel" =   1 ,"Le ménage ne dispose pas d’un emplacement réservé à son usage personnel" =   2 , "Non renseigné" =   9)  ,               
                   GELG = c("Le logement est équipé d'un groupe électrogène" =   1 ,"Le logement n'est pas équipé d'un groupe électrogène" =   2 , "Non renseigné" =   9)  ,               
                   GENREM =c("Homme"= 1,
                             "Femme" = 2),
                   ILNM= c("Nouvelle-Calédonie" = 1 ,
                           "Wallis-et-Futuna" = 2 ,
                           "Polynésie française" =3 ,
                           "Métropole, DOM ou autre territoire français" =4 ,
                           "Étranger"= 5 ),
                   INTER = c("Le logement dispose d’un accès à internet" =   1 ,"Le logement ne dispose pas d’un accès à internet" =   2 , "Non renseigné" =   9)  ,               
                   MAL = c( "Le logement est équipé d’une machine à laver" =1 ,"Le logement n’est pas équipé d’une machine à laver"= 2 , "Non renseigné" = 9 ),
                   NATM= c("Française (de naissance)"  = 1, 
                           "Française (par acquisition)"  = 2 ,
                           "Étrangère" = 3 ),
                   PEUPL = c("Peuplement normal"= "NOR","Sous-peuplement modéré"= "S01" ,"Sous-peuplement accentué"= "S02","Surpeuplement modéré"= "SU1" ,"Surpeuplement accentué"= "SU2"),
                   PSOL = c("Le logement est équipé de panneaux solaires" =   1 ,"Le logement n'est pas équipé de panneaux solaires" =   2 , "Non renseigné" =   9)  ,               
                   REFRI = c("Le logement est équipé d'un réfrigérateur" =   1 ,"Le logement n'est pas équipé d'un réfrigérateur" =   2 , "Non renseigné" =   9)  ,               
                   STOC = c("Propriétaire"  =  1 ,
                            "Locataire d’un logement vide" =   2 ,
                            "Locataire d’un logement meublé"  =  3 ,
                            "Logé gratuitement" =   4 ,
                            "Non renseigné" =  9 ),
                   
                   SURF =c("Moins de 30 m2" =  1 ,
                           "De 30 à moins de 40 m2"=  2 ,
                           "De 40 à moins de 60 m2"=  3 ,
                           "De 60 à moins de 80 m2" =  4 ,
                           "De 80 à moins de 100 m2" = 5 ,
                           "De 100 à moins de 1,20 m2" = 6 ,
                           "120 m2 ou plus" = 7 ,
                           "Non renseigné"  = 9 ),
                   
                   TACTM = c("Emploi" =1, 
                             "Apprentissage sous contrat ou stage rémunéré" =2, 
                             "Études ou stage non rémunéré" =3, 
                             "Chômage" = 4, 
                             "Retraite ou pré-retraite" = 5, 
                             "Femme ou homme au foyer" = 6, 
                             "Autre situation" = 7 ),
                   
                   TFIXE = c( "Le logement est équipé d'un téléphone fixe" =1 ,"Le logement n’est pas équipé d'un téléphone fixe"= 2 , "Non renseigné" = 9 ),
                   
                   TYPC14 = c("Maison" =1 ,"Appartement"=2 ,"Case mélanésienne" =3 ,"Construction provisoire, cabane"=4 ,"Bateau"  =5),
                   TYPEAU = c("Point d’eau individuel" =1 ,"Point d’eau collectif"=2 ),
                   TYPMENR=c(          "Personne seule" =  1, 
                                       "Couple sans enfant" =  2, 
                                       "Couple avec enfant(s)" =  3, 
                                       "Famille monoparentale" =  4, 
                                       "Autres : ménage complexe" =  5 ),
                   
                   WC = c( "Le logement est équipé de WC à l'intérieur" =1 ,"Le logement n’est pas équipé de WC à l'intérieur"= 2 , "Non renseigné" = 9 ))%>%
  mutate_if(sjlabelled::is_labelled,sjlabelled::as_label)



usethis::use_data(rp19_log, overwrite = TRUE)
